### ISSUE TITLE
`/favicon/*feed` fails to compute the feed param

### ISSUE THREAD

**Issue by eagletmt** [fastladder/fastladder#208]
When `/favicon/http://example.com/feed.rss` is requested, `url_from_path(:feed)` returns `on/http://example.com/feed.rss` because there's duplicated routing: `/icon/*feed` and `/favicon/*feed` .
`url_for(controller: :icon, action: :get, feed: '.')` always returns `/icon/.` .

There would be two solutions for it.

1. Unify the routing to `/favicon/*feed` (or `/icon/*feed` )
2. Change `url_from_path` so that it can handle such a situation

I'd rather choose the first one.

**Comment by makimoto** [comment]
+1 for the first one.
